### ISSUE TITLE
model run fine without OPTIMIZED_KERNEL_DIR=xtensa in tflm, but model run exception with OPTIMIZED_KERNEL_DIR=xtensa.

### ISSUE THREAD

**Issue by jiayue198509** [tensorflow/tflite-micro#740] opened 2021-11-26 08:23 UTC
model run fine without OPTIMIZED_KERNEL_DIR=xtensa in tflm, but model run exception with OPTIMIZED_KERNEL_DIR=xtensa.
[model.zip](https://github.com/tensorflow/tflite-micro/files/7607288/model.zip)
[error-log.txt](https://github.com/tensorflow/tflite-micro/files/7607289/error-log.txt)

**Comment by nyadla-sys** [comment] 2021-11-30 18:47
@cad-audio please have a look into this issue.

**Comment by jiayue198509** [comment] 2021-12-01 02:12
XTENSA_TOOLS_VERSION=RI-2020.5-linux
compile cmd：make -f tensorflow/lite/micro/tools/make/Makefile TARGET=xtensa OPTIMIZED_KERNEL_DIR=xtensa TARGET_ARCH=hifi5 XTENSA_CORE=Amlogic_v9 micro_speech_test BUILD_TYPE=release -j4

**Comment by jiayue198509** [comment] 2021-12-02 01:25
[micro_speech_test.zip](https://github.com/tensorflow/tflite-micro/files/7638182/micro_speech_test.zip)
you can use this application to  reproduce the issue.

**Comment by nyadla-sys** [comment] 2021-12-02 03:45
@jiayue198509 this seems to be binary ,could you please share the tflm test application source code that uses your model.

**Comment by jiayue198509** [comment] 2021-12-02 03:54
[src.zip](https://github.com/tensorflow/tflite-micro/files/7638889/src.zip)

**Comment by jiayue198509** [comment] 2021-12-06 07:20
@nyadla-sys have any progress？
If you need any more information, please let me know. Thanks！

**Comment by nyadla-sys** [comment] 2021-12-06 16:14
@jiayue198509 we could reproduce issue from our end and looking into our nnlib-hifi5 that we recently pushed on to Github.

**Comment by nyadla-sys** [comment] 2021-12-14 16:35
we found the issue with our NNLib-hifi5 and working on to fix the issue

**Comment by jiayue198509** [comment] 2022-04-01 06:45
@nyadla-sys have any progress？

**Comment by nyadla-sys** [comment] 2022-04-05 00:09
@cad-audio Bhanu could you please respond to his query?

**Comment by cad-audio** [comment] 2022-04-06 05:29
Hi @jiayue198509,

The issue is related to some alignment in xa_nn_matXvec_sym8sxasym8s_asym8s_circ().
and It is fixed in the latest HiFi 5 NN Library(v1.7.0).
I think tflite-micro master code uses the previous version of HiFi 5 NN Library (i.e. v1.6.0).

Thanks,
Bhanu

**Closed** 2022-04-24 05:58 UTC
